version: '3.8'

services:
  api:
    container_name: txt-share-api
    image: node
    ports: 
        - "3000:3000"
    volumes:
        - ./api:/usr/api
    working_dir: /usr/api
    command: bash -c "npm install && npm start"
    networks:
      - default
  web:
    container_name: txt-share-web
    depends_on:
      - api
    image: nginx:latest
    ports:
      - 8000:80
      - 8443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
      - ./certs:/etc/letsencrypt
      - ./logs:/var/log/nginx/
  certbot:
      image: certbot/certbot:latest
      volumes:
        - ./certs:/etc/letsencrypt
        - ./dist:/usr/share/nginx/html
      command: certonly --webroot --webroot-path=/usr/share/nginx/html --email allan@barcelos.dev --agree-tos --no-eff-email --staging --force-renewal
