version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: barcelos.dev
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
      - ./ssl:/etc/ssl
      - ./logs:/var/log/nginx/

