name: Deploy

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 0 * * *'

env:
  PRODUCTION: true
  # HTTPS: true
  # API: https://txtshare.barcelos.dev

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 16.x

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - uses: GuillaumeFalourd/setup-rsync@v1.1

      - run: npm ci
      # - run: npm run test:prod
      # - run: npm run lint
      - run: npm run build --aot --base-href=/

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}

      - name: Stop Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            folder="${{secrets.HOME}}/${{secrets.DOMAIN}}"
            if [ -d "$folder" ]; then
              cd ${{ secrets.HOME }}/${{ secrets.DOMAIN }}
              docker-compose down -v
            fi

      - name: Delete OLD Folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: rm -Rf ${{ secrets.HOME }}/${{ secrets.DOMAIN }}

      - name: Deploy with rsync
        run: |
          rsync --progress -avz -e "ssh -v -i ./.ssh/id_rsa" ./api ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.HOME }}/${{ secrets.DOMAIN }}/
          rsync --progress -avz -e "ssh -v -i ./.ssh/id_rsa" ./dist ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.HOME }}/${{ secrets.DOMAIN }}/
          rsync --progress -avz -e "ssh -v -i ./.ssh/id_rsa" ./docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.HOME }}/${{ secrets.DOMAIN }}/
          rsync --progress -avz -e "ssh -v -i ./.ssh/id_rsa" ./nginx.conf ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.HOME }}/${{ secrets.DOMAIN }}/

      - name: Start Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.HOME }}/${{ secrets.DOMAIN }}
            docker-compose up -d
